### ISSUE TITLE
Feature Tracker

### ISSUE THREAD

**Issue by zachcp** [zachcp/pymol_session_utils#6]
## PSE Parsing

- [x] Core Serde_pickle to Rust data structures
  - [x] pymol-molecule
  - [x] pymol-selection

- [ ]  Additional PSE Objects
  - [ ] pymol-gadget
  - [ ] PyObjectDist
  - [ ] PyObjectMap
  - [ ] PyObjectMesh
  - [ ] PyObjectSurface
  - [ ] PyObjectCGO
  - [ ] PyObjectAlignment
  - [ ] PyObjectGroup
  - [ ] PyObjectVolume
  - [ ] PyObjectCallback
  - [ ] PyObjectCurve

## MSVJ Core Logic

- [x] Nodes & Enums 
- [x] Builder methods
- [x]  msvj creation [tests](https://github.com/zachcp/pymol_session_utils/blob/main/tests/test_molview_spec.rs) for all of the [colab examples](https://colab.research.google.com/drive/1O2TldXlS01s-YgkD9gy87vWsfCBTYuz9)
- [ ] msvj creation for molviewspec [homepage examples](https://molstar.org/mol-view-spec/)

## PSE --> MSVJ

- [x] pse-to-pdb basic
- [ ] pse-to-pdb all PDB
- [x] pse-to-msvj-basic
- [x] URL encoding
- [ ] msvj selections
- [ ] msvj labels
- [ ] msvj color
- [ ] local running / testing
  - [ ] pdb export
  - [ ] msvj exprt
  - [ ] js/css and webserver from temp directory
